# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Veracode Upload & Scan

on:
  workflow_dispatch

jobs:
  build_scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -B package --file app/pom.xml

    - name: Veracode Scan
      run: java -jar VeracodeJavaAPI.jar -action uploadandscan -filepath app/target/verademo.war -vid '${{ secrets.VERACODE_API_ID }}' -vkey '${{ secrets.VERACODE_API_KEY }}' -version '${{ github.run_number }}' -autoscan true -appname GITHUB -createprofile true -deleteincompletescan 2 -scantimeout 60
           
